services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: 'redis://redis:6379'
    volumes:
      - .:/app

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - '6380:6379'

volumes:
  db_data:
